
#
# www.daytondv.org jekyll settings
#

# Site settings
title: Dayton Data Visualization
email: bowmanmc@gmail.com
description: Dayton Data Visualization Group
baseurl: ""
url: "http://www.daytondv.org"
twitter_username: daytondv
github_username:  daytondv

# Collections
collections:
    jobs:
        output: true
        permalink: /job/:path/
    sponsors:
        output: true
        permalink: /sponsor/:path/
    tutorials:
        output: true
        permalink: /tutorial/:path/

# Build settings
markdown: kramdown
